### ISSUE TITLE
Review #1 - Muy buen desafío.

### ISSUE THREAD

**Issue by FacundoEG** [fanziano/fanziano.github.io#1]
Hola Fanziano! como estas? estuve revisando un poco la pagina y la veo muy bien a modo de diseño! 

Los elementos responden en general muy bien a los cambios de resolución y se adaptan como corresponde, asi que te felicito por eso!

Te quiero dejar algunas sugerencias a modo visual para que tengas en cuenta que creo que se podrían mejorar.

Primero, fijate que el header en resoluciones muy amplias no termina de tomar todo el ancho que tiene, te recomiendo que al div.contenedor-nav le agreges la propiedad "justify-content: space-around" asi se acomoda con el ancho que tenga y de esta forma te quede mas centrado cuando tenga mucho ancho:

![Screenshot_20211229_110217](https://user-images.githubusercontent.com/79592789/147670269-8e2ce707-3ab4-472c-ab0e-3d42841b1d0e.png)

Despues de eso solo revisaría quizas el largo que llega a alcanzar el div.form, quizas con un "max-width" podrias revisar que solo llegue a cierto ancho y quede ahi. Creo que con un justify-content: center a la section-3 y sacandole el ancho a cuarto-titulo ya queda perfecto.

![Screenshot_20211229_110919](https://user-images.githubusercontent.com/79592789/147670824-bc4cff1f-fd50-4281-a426-7bac6aa23476.png)

De todas formas lo importante es que se mantiene bien y no se rompe! asi que tomalo como una sugerencia nada mas.

Como te digo la pagina quedo muy buena y cumple bien las consignas! asi que LGTM.

Te mando un saludo y te deseo exitos para lo proximo!

**Comment by fanziano** [comment]
Muchas gracias Facundo por todos tus comentarios y sobre todo por las sugerencias que me vienen bien para repasar nuevamente algunas partes del desafío. Saludos. Fernando.
